# fly.toml app configuration file generated for number-classification-api-gp0i7w on 2025-02-06T18:11:02Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "number-classification-api"

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
